config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  namespace :api do
    resources :account do
      get :get_cash
      get :load_cash
      get :balance
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base

  has_many :banknotes

  before_create :set_number

  def balance
    banknotes.sum(:denomination)
  end

  def available_banknotes(denomination)
    self.banknotes.where(denomination: denomination)
  end

  def get_cash(sum)
    GetCash.new(account: self.number, sum: sum).call
  end

  def charge(cash)
    LoadCash.new(account: self.number, cash: cash).call
  end

  private

  def set_number
    self.number = generate_number
  end

  def generate_number
    loop do
      number = SecureRandom.hex(3).upcase
      break number unless Account.exists?(number: number)
    end
  end

end

app/models/banknote.rb
class Banknote < ActiveRecord::Base

  belongs_to :account

  DENOMINATION_SCOPE = [1,2,5,10,25,50]

  validates :account, presence: true
  validates :denomination, presence: true, numericality: {greater_than_or_equal_to:  1}, on: :create
  validates :denomination, inclusion: { in: DENOMINATION_SCOPE,
                                        message: "%{value} is not a valid denomination" }


  before_create :add_data

  private

  def add_data
    self.description = 'bank of USA'
    self.title = "#{self.denomination}$"
  end

end

app/controllers/api/account_controller.rb
class Api::AccountController < ApplicationController
  require 'json'

   before_action :check_account, only: [:balance, :load_cash, :get_cash]

  def new

    account = Account.create
    render json: {account: account.number, balance: account.balance}, status: :ok

  end

  def balance

    render json: {account: account.number, balance: account.balance}, status: :ok

  end

  def load_cash

      request = account.charge(params[:cash])

      if request[:message] == 'success'
        render json: {account: account.number, balance: account.balance}, status: :ok
      else
        render json: {account: account.number, message: request[:message]}, status: :ok
      end

  end

  def get_cash

      request = account.get_cash(params[:sum])

      if request[:message] == 'success' && account.banknotes.where(id: request[:cash]).delete_all
        render json: {account: account.number, money: request[:cash].map {|c| c.title}, balance: account.balance}, status: :ok
      else
        render json: {account: account.number, message: request[:message]}, status: :ok
      end

  end

  private

  def check_account

    if account.blank?
      render json: {account: params[:account_id], message: "Not Found"}, status: :ok
    end

  end


  def account

    @account ||= Account.find_by number: params[:account_id]

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @account = Account.last
    @sum = 119
    @cash = '[{"denomination":1,"amount":100},{"denomination":2,"amount":50},{"denomination":5,"amount":25},{"denomination":1,"amount":20},{"denomination":25,"amount":10},{"denomination":50,"amount":10}]'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Training</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<p><%= link_to "New Account", new_api_account_path %></p>
<% if @account.present? %>
  <h1>Account ID - <%= @account.number %></h1>
  <p><%= link_to "Show Balance", api_account_balance_path(@account.number), remote: true %></p>
  <p>
    <%= link_to "Get Cash", api_account_get_cash_path(@account.number, sum: @sum),id: "get-cash-link", remote: true %>
    <%= number_field_tag "sum", @sum %>
  </p>
  <p><%= link_to "Load Cash", api_account_load_cash_path(@account.number, cash: @cash), remote: true %></p>
  <div class="result">
    <h1>Result</h1>

  </div>
<% end %>
<script>
  $('#sum').on("keyup", function () {
    console.log("<%= api_account_get_cash_path(@account.number) %>?sum=" + this.value);
    $('#get-cash-link').attr('href',"<%= api_account_get_cash_path(@account.number) %>?sum=" + this.value)
  });

  $('a').on("ajax:success", function (event, data, status, xhr) {
    $('.result').append("<p>" + JSON.stringify(data) + "</p>");
  });
</script>